version: 2

builds:
  - id: default
    main: ./cmd/main.go
    binary: http-loadgen
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: ['tar.gz', 'zip']
    name_template: "http-loadgen_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - api/**
      - config/**
      - scripts/**
      - docker-compose.yml
      - docker-compose.override.yml
      - haproxy/haproxy.cfg
      - prometheus/**

dockers:
  - image_templates:
      - "virag/http-loadgen:latest"
      - "virag/http-loadgen:{{ .Tag }}"
    dockerfile: ./Dockerfile

checksum:
  name_template: "checksums.txt"
