version: 2

before:
  hooks:
    - mkdir -p .goreleaser-docker
    - cp -r config .goreleaser-docker/
    - cp -r api .goreleaser-docker/
    - cp Dockerfile .goreleaser-docker/
    - cp -r cmd .goreleaser-docker/
    - cp go.mod go.sum .goreleaser-docker/

builds:
  - id: default
    main: ./cmd/main.go
    binary: http-loadgen
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: ['tar.gz', 'zip']
    name_template: "http-loadgen_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - api/**
      - config/**
      - scripts/**
      - docker-compose.yml
      - docker-compose.override.yml
      - haproxy/haproxy.cfg
      - prometheus/**

dockers:
  - image_templates:
      - "virag/http-loadgen:latest"
      - "virag/http-loadgen:{{ .Tag }}"
    dockerfile: .goreleaser-docker/Dockerfile
    use: buildx

checksum:
  name_template: "checksums.txt"
