dsn: postgresql://root@host.docker.internal:26257/defaultdb?sslmode=disable

namespaces:
  - id: 0
    name: documents
  - id: 1
    name: users

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467

log:
  level: debug
