api:
  write_api: "http://localhost:4467"     # Used for tuple insertions (PUT)
  read_api: "http://localhost:4466"      # Used for permission checks (POST)

requests:
  write:
    method: PUT
    url: "{{ .WriteAPI }}/admin/relation-tuples"
    headers:
      Content-Type: application/json
    body: |
      {
        "namespace": "documents",
        "object": "{{ .object }}",
        "relation": "viewer",
        "subject_id": "user:{{ .subject }}"
      }

  read:
    method: POST
    url: "{{ .ReadAPI }}/relation-tuples/check"
    headers:
      Content-Type: application/json
    body: |
      {
        "namespace": "documents",
        "object": "{{ .object }}",
        "relation": "viewer",
        "subject_id": "user:{{ .subject }}"
      }

workload:
  concurrency: 10                        # Number of total goroutines (1 writer + 9 readers for 100:1 ratio)
  checks_per_second: 1000                # Global rate limit for permission checks
  read_ratio: 100                        # For every write, ~100 reads will be attempted
  duration_sec: 30                       # Run duration in seconds
  max_retries: 3                         # Max retry attempts for write/read failures
  retry_delay_ms: 200                    # Delay between retries in milliseconds
  request_timeout_sec: 10
  max_open_conns: 200
  max_idle_conns: 200
  verbose: false                         # Enable detailed logs for each write/read
